apiVersion: v1
kind: Service
metadata:
  name: ssh-tunnel-proxy-svc
  labels:
    app: ssh-tunnel-proxy
    revision: ${REVISION}
spec:
  type: LoadBalancer
  ports:
  - port: 22
    protocol: TCP
  selector:
    app: ssh-tunnel-proxy
